version: '3.0.7'
services:
  backend:
    image: 'fullstackdoni/spawn'
    container_name: 'backend-container'
    depends_on:
      - mysql
    environment:
      - SERVER_PORT=9999
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/spawn
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    ports:
      - 8080:9999
  mysql:
    image: 'mysql'
    container_name: 'mysql-container'
    environment:
      - MYSQL_DATABASE=spawn
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 2345:3306