version: '3.0.7'
services:
  backend:
    container_name: 'backend-container'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:9999
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/spawn
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.jdbc.Driver
      - SERVER_PORT=9999
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_JPA_SHOW_SQL=true
  mysql:
    image: mysql:latest
    container_name: 'mysql-container'
    ports:
      - 2345:3306
    environment:
      - MYSQL_DATABASE=spawn
      - MYSQL_ROOT_PASSWORD=root